<?php

namespace App\Model;

class Countries
{
    public function getCountriesList(): array
    {
        return 
            [
                ['country_code' => 'AF', 'country' => 'Afghanistan'],
                ['country_code' => 'ZA', 'country' => 'Afrique du Sud'],
                ['country_code' => 'AL', 'country' => 'Albanie'],
                ['country_code' => 'DZ', 'country' => 'Algérie'],
                ['country_code' => 'DE', 'country' => 'Allemagne'],
                ['country_code' => 'AD', 'country' => 'Andorre'],
                ['country_code' => 'AO', 'country' => 'Angola'],
                ['country_code' => 'AI', 'country' => 'Anguilla'],
                ['country_code' => 'AQ', 'country' => 'Antarctique'],
                ['country_code' => 'AG', 'country' => 'Antigua-et-Barbuda'],
                ['country_code' => 'AN', 'country' => 'Antilles néerlandaises'],
                ['country_code' => 'SA', 'country' => 'Arabie saoudite'],
                ['country_code' => 'AR', 'country' => 'Argentine'],
                ['country_code' => 'AM', 'country' => 'Arménie'],
                ['country_code' => 'AW', 'country' => 'Aruba'],
                ['country_code' => 'AU', 'country' => 'Australie'],
                ['country_code' => 'AT', 'country' => 'Autriche'],
                ['country_code' => 'AZ', 'country' => 'Azerbaïdjan'],
                ['country_code' => 'BS', 'country' => 'Bahamas'],
                ['country_code' => 'BH', 'country' => 'Bahreïn'],
                ['country_code' => 'BD', 'country' => 'Bangladesh'],
                ['country_code' => 'BB', 'country' => 'Barbade'],
                ['country_code' => 'PW', 'country' => 'Belau'],
                ['country_code' => 'BE', 'country' => 'Belgique'],
                ['country_code' => 'BZ', 'country' => 'Belize'],
                ['country_code' => 'BJ', 'country' => 'Bénin'],
                ['country_code' => 'BM', 'country' => 'Bermudes'],
                ['country_code' => 'BT', 'country' => 'Bhoutan'],
                ['country_code' => 'BY', 'country' => 'Biélorussie'],
                ['country_code' => 'MM', 'country' => 'Birmanie'],
                ['country_code' => 'BO', 'country' => 'Bolivie'],
                ['country_code' => 'BA', 'country' => 'Bosnie-Herzégovine'],
                ['country_code' => 'BW', 'country' => 'Botswana'],
                ['country_code' => 'BR', 'country' => 'Brésil'],
                ['country_code' => 'BN', 'country' => 'Brunei'],
                ['country_code' => 'BG', 'country' => 'Bulgarie'],
                ['country_code' => 'BF', 'country' => 'Burkina Faso'],
                ['country_code' => 'BI', 'country' => 'Burundi'],
                ['country_code' => 'KH', 'country' => 'Cambodge'],
                ['country_code' => 'CM', 'country' => 'Cameroun'],
                ['country_code' => 'CA', 'country' => 'Canada'],
                ['country_code' => 'CV', 'country' => 'Cap-Vert'],
                ['country_code' => 'CL', 'country' => 'Chili'],
                ['country_code' => 'CN', 'country' => 'Chine'],
                ['country_code' => 'CY', 'country' => 'Chypre'],
                ['country_code' => 'CO', 'country' => 'Colombie'],
                ['country_code' => 'KM', 'country' => 'Comores'],
                ['country_code' => 'CG', 'country' => 'Congo'],
                ['country_code' => 'KP', 'country' => 'Corée du Nord'],
                ['country_code' => 'KR', 'country' => 'Corée du Sud'],
                ['country_code' => 'CR', 'country' => 'Costa Rica'],
                ['country_code' => 'CI', 'country' => 'Côte d\'Ivoire'],
                ['country_code' => 'HR', 'country' => 'Croatie'],
                ['country_code' => 'CU', 'country' => 'Cuba'],
                ['country_code' => 'DK', 'country' => 'Danemark'],
                ['country_code' => 'DJ', 'country' => 'Djibouti'],
                ['country_code' => 'DM', 'country' => 'Dominique'],
                ['country_code' => 'EG', 'country' => 'Égypte'],
                ['country_code' => 'AE', 'country' => 'Émirats arabes unis'],
                ['country_code' => 'EC', 'country' => 'Équateur'],
                ['country_code' => 'ER', 'country' => 'Érythrée'],
                ['country_code' => 'ES', 'country' => 'Espagne'],
                ['country_code' => 'EE', 'country' => 'Estonie'],
                ['country_code' => 'US', 'country' => 'États-Unis'],
                ['country_code' => 'ET', 'country' => 'Éthiopie'],
                ['country_code' => 'FI', 'country' => 'Finlande'],
                ['country_code' => 'FR', 'country' => 'France'],
                ['country_code' => 'GA', 'country' => 'Gabon'],
                ['country_code' => 'GM', 'country' => 'Gambie'],
                ['country_code' => 'GE', 'country' => 'Géorgie'],
                ['country_code' => 'GH', 'country' => 'Ghana'],
                ['country_code' => 'GI', 'country' => 'Gibraltar'],
                ['country_code' => 'GR', 'country' => 'Grèce'],
                ['country_code' => 'GD', 'country' => 'Grenade'],
                ['country_code' => 'GL', 'country' => 'Groenland'],
                ['country_code' => 'GP', 'country' => 'Guadeloupe'],
                ['country_code' => 'GU', 'country' => 'Guam'],
                ['country_code' => 'GT', 'country' => 'Guatemala'],
                ['country_code' => 'GN', 'country' => 'Guinée'],
                ['country_code' => 'GQ', 'country' => 'Guinée équatoriale'],
                ['country_code' => 'GW', 'country' => 'Guinée-Bissao'],
                ['country_code' => 'GY', 'country' => 'Guyana'],
                ['country_code' => 'GF', 'country' => 'Guyane française'],
                ['country_code' => 'HT', 'country' => 'Haïti'],
                ['country_code' => 'HN', 'country' => 'Honduras'],
                ['country_code' => 'HK', 'country' => 'Hong Kong'],
                ['country_code' => 'HU', 'country' => 'Hongrie'],
                ['country_code' => 'BV', 'country' => 'Ile Bouvet'],
                ['country_code' => 'CX', 'country' => 'Ile Christmas'],
                ['country_code' => 'NF', 'country' => 'Ile Norfolk'],
                ['country_code' => 'KY', 'country' => 'Iles Cayman'],
                ['country_code' => 'CK', 'country' => 'Iles Cook'],
                ['country_code' => 'CC', 'country' => 'Iles des Cocos (Keeling)'],
                ['country_code' => 'FK', 'country' => 'Iles Falkland'],
                ['country_code' => 'FO', 'country' => 'Iles Féroé'],
                ['country_code' => 'FJ', 'country' => 'Iles Fidji'],
                ['country_code' => 'GS', 'country' => 'Iles Géorgie du Sud et Sandwich du Sud'],
                ['country_code' => 'HM', 'country' => 'Iles Heard et McDonald'],
                ['country_code' => 'MH', 'country' => 'Iles Marshall'],
                ['country_code' => 'UM', 'country' => 'Iles mineures éloignées des États-Unis'],
                ['country_code' => 'PN', 'country' => 'Iles Pitcairn'],
                ['country_code' => 'SB', 'country' => 'Iles Salomon'],
                ['country_code' => 'SJ', 'country' => 'Iles Svalbard et Jan Mayen'],
                ['country_code' => 'TC', 'country' => 'Iles Turks-et-Caicos'],
                ['country_code' => 'VI', 'country' => 'Iles Vierges américaines'],
                ['country_code' => 'VG', 'country' => 'Iles Vierges britanniques'],
                ['country_code' => 'IN', 'country' => 'Inde'],
                ['country_code' => 'ID', 'country' => 'Indonésie'],
                ['country_code' => 'IR', 'country' => 'Iran'],
                ['country_code' => 'IQ', 'country' => 'Iraq'],
                ['country_code' => 'IE', 'country' => 'Irlande'],
                ['country_code' => 'IS', 'country' => 'Islande'],
                ['country_code' => 'IL', 'country' => 'Israël'],
                ['country_code' => 'IT', 'country' => 'Italie'],
                ['country_code' => 'JM', 'country' => 'Jamaïque'],
                ['country_code' => 'JP', 'country' => 'Japon'],
                ['country_code' => 'JO', 'country' => 'Jordanie'],
                ['country_code' => 'KZ', 'country' => 'Kazakhstan'],
                ['country_code' => 'KE', 'country' => 'Kenya'],
                ['country_code' => 'KG', 'country' => 'Kirghizistan'],
                ['country_code' => 'KI', 'country' => 'Kiribati'],
                ['country_code' => 'KW', 'country' => 'Koweït'],
                ['country_code' => 'LA', 'country' => 'Laos'],
                ['country_code' => 'LS', 'country' => 'Lesotho'],
                ['country_code' => 'LV', 'country' => 'Lettonie'],
                ['country_code' => 'LB', 'country' => 'Liban'],
                ['country_code' => 'LR', 'country' => 'Liberia'],
                ['country_code' => 'LY', 'country' => 'Libye'],
                ['country_code' => 'LI', 'country' => 'Liechtenstein'],
                ['country_code' => 'LT', 'country' => 'Lituanie'],
                ['country_code' => 'LU', 'country' => 'Luxembourg'],
                ['country_code' => 'MO', 'country' => 'Macao'],
                ['country_code' => 'MK', 'country' => 'Macédoine'],
                ['country_code' => 'MG', 'country' => 'Madagascar'],
                ['country_code' => 'MY', 'country' => 'Malaisie'],
                ['country_code' => 'MW', 'country' => 'Malawi'],
                ['country_code' => 'MV', 'country' => 'Maldives'],
                ['country_code' => 'ML', 'country' => 'Mali'],
                ['country_code' => 'MT', 'country' => 'Malte'],
                ['country_code' => 'MP', 'country' => 'Mariannes du Nord'],
                ['country_code' => 'MA', 'country' => 'Maroc'],
                ['country_code' => 'MQ', 'country' => 'Martinique'],
                ['country_code' => 'MU', 'country' => 'Maurice'],
                ['country_code' => 'MR', 'country' => 'Mauritanie'],
                ['country_code' => 'YT', 'country' => 'Mayotte'],
                ['country_code' => 'MX', 'country' => 'Mexique'],
                ['country_code' => 'FM', 'country' => 'Micronésie'],
                ['country_code' => 'MD', 'country' => 'Moldavie'],
                ['country_code' => 'MC', 'country' => 'Monaco'],
                ['country_code' => 'MN', 'country' => 'Mongolie'],
                ['country_code' => 'MS', 'country' => 'Montserrat'],
                ['country_code' => 'MZ', 'country' => 'Mozambique'],
                ['country_code' => 'NA', 'country' => 'Namibie'],
                ['country_code' => 'NR', 'country' => 'Nauru'],
                ['country_code' => 'NP', 'country' => 'Népal'],
                ['country_code' => 'NI', 'country' => 'Nicaragua'],
                ['country_code' => 'NE', 'country' => 'Niger'],
                ['country_code' => 'NG', 'country' => 'Nigeria'],
                ['country_code' => 'NU', 'country' => 'Nioué'],
                ['country_code' => 'NO', 'country' => 'Norvège'],
                ['country_code' => 'NC', 'country' => 'Nouvelle-Calédonie'],
                ['country_code' => 'NZ', 'country' => 'Nouvelle-Zélande'],
                ['country_code' => 'OM', 'country' => 'Oman'],
                ['country_code' => 'UG', 'country' => 'Ouganda'],
                ['country_code' => 'UZ', 'country' => 'Ouzbékistan'],
                ['country_code' => 'PK', 'country' => 'Pakistan'],
                ['country_code' => 'PA', 'country' => 'Panama'],
                ['country_code' => 'PG', 'country' => 'Papouasie-Nouvelle-Guinée'],
                ['country_code' => 'PY', 'country' => 'Paraguay'],
                ['country_code' => 'NL', 'country' => 'Pays-Bas'],
                ['country_code' => 'PE', 'country' => 'Pérou'],
                ['country_code' => 'PH', 'country' => 'Philippines'],
                ['country_code' => 'PL', 'country' => 'Pologne'],
                ['country_code' => 'PF', 'country' => 'Polynésie française'],
                ['country_code' => 'PR', 'country' => 'Porto Rico'],
                ['country_code' => 'PT', 'country' => 'Portugal'],
                ['country_code' => 'QA', 'country' => 'Qatar'],
                ['country_code' => 'CF', 'country' => 'République centrafricaine'],
                ['country_code' => 'CD', 'country' => 'République démocratique du Congo'],
                ['country_code' => 'DO', 'country' => 'République dominicaine'],
                ['country_code' => 'CZ', 'country' => 'République tchèque'],
                ['country_code' => 'RE', 'country' => 'Réunion'],
                ['country_code' => 'RO', 'country' => 'Roumanie'],
                ['country_code' => 'GB', 'country' => 'Royaume-Uni'],
                ['country_code' => 'RU', 'country' => 'Russie'],
                ['country_code' => 'RW', 'country' => 'Rwanda'],
                ['country_code' => 'EH', 'country' => 'Sahara occidental'],
                ['country_code' => 'KN', 'country' => 'Saint-Christophe-et-Niévès'],
                ['country_code' => 'SH', 'country' => 'Sainte-Hélène'],
                ['country_code' => 'LC', 'country' => 'Sainte-Lucie'],
                ['country_code' => 'SM', 'country' => 'Saint-Marin'],
                ['country_code' => 'PM', 'country' => 'Saint-Pierre-et-Miquelon'],
                ['country_code' => 'VA', 'country' => 'Saint-Siège '],
                ['country_code' => 'VC', 'country' => 'Saint-Vincent-et-les-Grenadines'],
                ['country_code' => 'SV', 'country' => 'Salvador'],
                ['country_code' => 'WS', 'country' => 'Samoa'],
                ['country_code' => 'AS', 'country' => 'Samoa américaines'],
                ['country_code' => 'ST', 'country' => 'Sao Tomé-et-Principe'],
                ['country_code' => 'SN', 'country' => 'Sénégal'],
                ['country_code' => 'SC', 'country' => 'Seychelles'],
                ['country_code' => 'SL', 'country' => 'Sierra Leone'],
                ['country_code' => 'SG', 'country' => 'Singapour'],
                ['country_code' => 'SK', 'country' => 'Slovaquie'],
                ['country_code' => 'SI', 'country' => 'Slovénie'],
                ['country_code' => 'SO', 'country' => 'Somalie'],
                ['country_code' => 'SD', 'country' => 'Soudan'],
                ['country_code' => 'LK', 'country' => 'Sri Lanka'],
                ['country_code' => 'SE', 'country' => 'Suède'],
                ['country_code' => 'CH', 'country' => 'Suisse'],
                ['country_code' => 'SR', 'country' => 'Suriname'],
                ['country_code' => 'SZ', 'country' => 'Swaziland'],
                ['country_code' => 'SY', 'country' => 'Syrie'],
                ['country_code' => 'TJ', 'country' => 'Tadjikistan'],
                ['country_code' => 'TW', 'country' => 'Taïwan'],
                ['country_code' => 'TZ', 'country' => 'Tanzanie'],
                ['country_code' => 'TD', 'country' => 'Tchad'],
                ['country_code' => 'TF', 'country' => 'Terres australes françaises'],
                ['country_code' => 'IO', 'country' => 'Territoire britannique de l\'Océan Indien'],
                ['country_code' => 'TH', 'country' => 'Thaïlande'],
                ['country_code' => 'TL', 'country' => 'Timor Oriental'],
                ['country_code' => 'TG', 'country' => 'Togo'],
                ['country_code' => 'TK', 'country' => 'Tokélaou'],
                ['country_code' => 'TO', 'country' => 'Tonga'],
                ['country_code' => 'TT', 'country' => 'Trinité-et-Tobago'],
                ['country_code' => 'TN', 'country' => 'Tunisie'],
                ['country_code' => 'TM', 'country' => 'Turkménistan'],
                ['country_code' => 'TR', 'country' => 'Turquie'],
                ['country_code' => 'TV', 'country' => 'Tuvalu'],
                ['country_code' => 'UA', 'country' => 'Ukraine'],
                ['country_code' => 'UY', 'country' => 'Uruguay'],
                ['country_code' => 'VU', 'country' => 'Vanuatu'],
                ['country_code' => 'VE', 'country' => 'Venezuela'],
                ['country_code' => 'VN', 'country' => 'Vietnam'],
                ['country_code' => 'WF', 'country' => 'Wallis-et-Futuna'],
                ['country_code' => 'YE', 'country' => 'Yémen'],
                ['country_code' => 'YU', 'country' => 'Yougoslavie'],
                ['country_code' => 'ZM', 'country' => 'Zambie'],
                ['country_code' => 'ZW', 'country' => 'Zimbabwe']
            ];
    }

}